---
- hosts: localhost
  connection: local
  tasks:
    - name: Test that my module works
      rax_dns_setup:
        region: SYD
        credsfile: credsfile.txt
        debugfile: filename.txt




